CREATE TABLE IF NOT EXISTS task_definitions (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    command VARCHAR(4000) NOT NULL,
    working_directory VARCHAR(1000),
    timeout_millis BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS task_runs (
    id VARCHAR(64) PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    exit_code INTEGER,
    error_message VARCHAR(4000),
    attempt INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    CONSTRAINT fk_task_runs_task_id FOREIGN KEY (task_id) REFERENCES task_definitions(id)
);

CREATE TABLE IF NOT EXISTS task_schedules (
    id VARCHAR(64) PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL,
    cron_expression VARCHAR(255),
    fixed_delay_millis BIGINT,
    next_run_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_schedules_task_id FOREIGN KEY (task_id) REFERENCES task_definitions(id)
);

CREATE TABLE IF NOT EXISTS task_run_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    stream VARCHAR(32) NOT NULL,
    message VARCHAR(4000) NOT NULL,
    CONSTRAINT fk_task_run_logs_run_id FOREIGN KEY (run_id) REFERENCES task_runs(id)
);
